[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
dependencies = [
    "paho-mqtt",
    "adafruit-circuitpython-seesaw",
    "adafruit-circuitpython-ahtx0",
    "adafruit-circuitpython-bh1750",
]
build-backend = "setuptools.build_meta"